[package]
name = "moxie-native"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffnixen@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.20.0"
gleam = "0.6.2"
glutin = "0.22.0"
scopeguard = "1"
euclid = "0.20.3"
slotmap = "0.4"
font-kit = "0.4.0"
proc-macro-hack = "0.5"
proc-macro-nested = "0.1.3"

[dependencies.illicit]
git = "https://github.com/anp/moxie.git"
rev = "08600d4c30457d84a483eeec8092276eb199254b"

[dependencies.moxie]
git = "https://github.com/anp/moxie.git"
rev = "08600d4c30457d84a483eeec8092276eb199254b"

[dependencies.topo]
git = "https://github.com/anp/moxie.git"
rev = "08600d4c30457d84a483eeec8092276eb199254b"

[dependencies.webrender]
git = "https://github.com/servo/webrender.git"
rev = "11954418bcced3d611806541718ba951bad98765"

[dependencies.skribo]
git = "https://github.com/tiffany352/skribo.git"
rev = "de744e106547c6c62fc431928e2bd575e6f66a2e"

[dependencies.moxie-native-style]
path = "./style"

[dependencies.moxie-native-mox]
path = "./mox"

[workspace]
members = [
    "devtools",
    "devtools_example",
]
